# WARNING:::1000 API CALLS PER DAY!:::WARNING
$$Will-call-almost-900-times-on-one-run!$$

### Download weekly weather data since the start of our data

In [1]:
from datetime import datetime as dt, timedelta
from darksky import forecast

In [2]:
def convert_to_unix(time):
    return time.timestamp()

In [3]:
def add_week_in_unix(start):
    seconds_in_minute = 60
    
    if not isinstance(start, int):
        print("GET YOUR STARTING TIME INTO UNIX FORMAT FIRST!")
    
    return start + timedelta(days=7).total_seconds()

In [4]:
Johns_api_key = '99870465df482cbe2825dbd41af11496'
Auss_api_key = '80307cf49421357d3b006ce2205e8d58'

In [5]:
starting_date = 978346800
weeks_to_look = 893 # match row count of weekly_diseases output

In [6]:
berlin = (52.520008, 13.404954)

In [7]:
def load_data_from_location(location, weeks_to_look, starting_date, api_key):    
    temperature_per_week = []
    windspeed_per_week = []
    humidity_per_week = []
    pressure_per_week = []

    date = starting_date

    for week in range(weeks_to_look):
        try:
            location_at_week = forecast(api_key, location[0], location[1], 
                                        time=date, 
                                        units='si')
        except:
            print("Failed to access API!")
        
        try:
            temperature_per_week.append(location_at_week.temperature)
        except:
            temperature_per_week.append(None)
        try:
            windspeed_per_week.append(location_at_week.windSpeed)
        except:
            windspeed_per_week.append(None)
        try:
            humidity_per_week.append(location_at_week.humidity)
        except:
            humidity_per_week.append(None)
        try:
            pressure_per_week.append(location_at_week.pressure)
        except:
            pressure_per_week.append(None)
        
        print('LOADED:', dt.fromtimestamp(date).strftime('%Y-%m-%d'), 'call number:', week+1)
        
        date = round(add_week_in_unix(date))
            
    return temperature_per_week, windspeed_per_week, humidity_per_week, pressure_per_week

In [8]:
temp, wind, humid, press = load_data_from_location(berlin, weeks_to_look, starting_date, Auss_api_key)

LOADED: 2001-01-01 call number: 1
LOADED: 2001-01-08 call number: 2
LOADED: 2001-01-15 call number: 3
LOADED: 2001-01-22 call number: 4
LOADED: 2001-01-29 call number: 5
LOADED: 2001-02-05 call number: 6
LOADED: 2001-02-12 call number: 7
LOADED: 2001-02-19 call number: 8
LOADED: 2001-02-26 call number: 9
LOADED: 2001-03-05 call number: 10
LOADED: 2001-03-12 call number: 11
LOADED: 2001-03-19 call number: 12
LOADED: 2001-03-26 call number: 13
LOADED: 2001-04-02 call number: 14
LOADED: 2001-04-09 call number: 15
LOADED: 2001-04-16 call number: 16
LOADED: 2001-04-23 call number: 17
LOADED: 2001-04-30 call number: 18
LOADED: 2001-05-07 call number: 19
LOADED: 2001-05-14 call number: 20
LOADED: 2001-05-21 call number: 21
LOADED: 2001-05-28 call number: 22
LOADED: 2001-06-04 call number: 23
LOADED: 2001-06-11 call number: 24
LOADED: 2001-06-18 call number: 25
LOADED: 2001-06-25 call number: 26
LOADED: 2001-07-02 call number: 27
LOADED: 2001-07-09 call number: 28
LOADED: 2001-07-16 call numbe

LOADED: 2005-06-06 call number: 232
LOADED: 2005-06-13 call number: 233
LOADED: 2005-06-20 call number: 234
LOADED: 2005-06-27 call number: 235
LOADED: 2005-07-04 call number: 236
LOADED: 2005-07-11 call number: 237
LOADED: 2005-07-18 call number: 238
LOADED: 2005-07-25 call number: 239
LOADED: 2005-08-01 call number: 240
LOADED: 2005-08-08 call number: 241
LOADED: 2005-08-15 call number: 242
LOADED: 2005-08-22 call number: 243
LOADED: 2005-08-29 call number: 244
LOADED: 2005-09-05 call number: 245
LOADED: 2005-09-12 call number: 246
LOADED: 2005-09-19 call number: 247
LOADED: 2005-09-26 call number: 248
LOADED: 2005-10-03 call number: 249
LOADED: 2005-10-10 call number: 250
LOADED: 2005-10-17 call number: 251
LOADED: 2005-10-24 call number: 252
LOADED: 2005-10-31 call number: 253
LOADED: 2005-11-07 call number: 254
LOADED: 2005-11-14 call number: 255
LOADED: 2005-11-21 call number: 256
LOADED: 2005-11-28 call number: 257
LOADED: 2005-12-05 call number: 258
LOADED: 2005-12-12 call numb

LOADED: 2009-10-19 call number: 460
LOADED: 2009-10-26 call number: 461
LOADED: 2009-11-02 call number: 462
LOADED: 2009-11-09 call number: 463
LOADED: 2009-11-16 call number: 464
LOADED: 2009-11-23 call number: 465
LOADED: 2009-11-30 call number: 466
LOADED: 2009-12-07 call number: 467
LOADED: 2009-12-14 call number: 468
LOADED: 2009-12-21 call number: 469
LOADED: 2009-12-28 call number: 470
LOADED: 2010-01-04 call number: 471
LOADED: 2010-01-11 call number: 472
LOADED: 2010-01-18 call number: 473
LOADED: 2010-01-25 call number: 474
LOADED: 2010-02-01 call number: 475
LOADED: 2010-02-08 call number: 476
LOADED: 2010-02-15 call number: 477
LOADED: 2010-02-22 call number: 478
LOADED: 2010-03-01 call number: 479
LOADED: 2010-03-08 call number: 480
LOADED: 2010-03-15 call number: 481
LOADED: 2010-03-22 call number: 482
LOADED: 2010-03-29 call number: 483
LOADED: 2010-04-05 call number: 484
LOADED: 2010-04-12 call number: 485
LOADED: 2010-04-19 call number: 486
LOADED: 2010-04-26 call numb

LOADED: 2014-03-03 call number: 688
LOADED: 2014-03-10 call number: 689
LOADED: 2014-03-17 call number: 690
LOADED: 2014-03-24 call number: 691
LOADED: 2014-03-31 call number: 692
LOADED: 2014-04-07 call number: 693
LOADED: 2014-04-14 call number: 694
LOADED: 2014-04-21 call number: 695
LOADED: 2014-04-28 call number: 696
LOADED: 2014-05-05 call number: 697
LOADED: 2014-05-12 call number: 698
LOADED: 2014-05-19 call number: 699
LOADED: 2014-05-26 call number: 700
LOADED: 2014-06-02 call number: 701
LOADED: 2014-06-09 call number: 702
LOADED: 2014-06-16 call number: 703
LOADED: 2014-06-23 call number: 704
LOADED: 2014-06-30 call number: 705
LOADED: 2014-07-07 call number: 706
LOADED: 2014-07-14 call number: 707
LOADED: 2014-07-21 call number: 708
LOADED: 2014-07-28 call number: 709
LOADED: 2014-08-04 call number: 710
LOADED: 2014-08-11 call number: 711
LOADED: 2014-08-18 call number: 712
LOADED: 2014-08-25 call number: 713
LOADED: 2014-09-01 call number: 714
LOADED: 2014-09-08 call numb

In [13]:
import numpy as np

temp_a = np.asarray(temp)
wind_a = np.asarray(wind)
humid_a = np.asarray(humid)
press_a = np.asarray(press)

print(temp_a[:5])
print(wind_a[:5])
print(humid_a[:5])
print(press_a[:5])

weather_data = np.vstack((temp_a, wind_a))
weather_data = np.vstack((weather_data, humid_a))
weather_data = np.vstack((weather_data, press_a))

print(weather_data[0][:5])
print(weather_data[1][:5])
print(weather_data[2][:5])
print(weather_data[3][:5])

[ 0.24  3.73 -1.87 -1.71  2.6 ]
[ 3.19  1.51  1.01  4.8   2.11]
[ 0.9   0.92  0.92  0.88  0.97]
[1003.58 1013.08 1035.67 1018.92 1014.28]
[0.24 3.73 -1.87 -1.71 2.6]
[3.19 1.51 1.01 4.8 2.11]
[0.9 0.92 0.92 0.88 0.97]
[1003.58 1013.08 1035.67 1018.92 1014.28]


In [14]:
import pickle as pk

pk.dump(weather_data, open("weather_data.pkl", "wb"))
np.save('weather_data_np', weather_data)